apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.deployment.files }}
  {{ $key }}:
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}
