apiVersion: v1
appVersion: 3.2.0
description: A reverse proxy that provides authentication with Google, Github or other
  providers
engine: gotpl
home: http://www.videntity.com/
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
maintainers:
- email: maxime@root314.com
  name: miouge1
name: oauth2-proxy
sources:
- https://github.com/pusher/oauth2_proxy
version: 0.13.0
